name: Build Component
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cargo-component
        run: cargo install --locked cargo-component

      - name: Install wasm-tools
        run: cargo install --locked wasm-tools

      - name: Install wkg
        run: cargo install --locked wkg

      - name: Build component
        run: wkg wit build --output math.wasm

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: math-wasm
          path: math.wasm
          retention-days: 30

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download WASM artifact
        uses: actions/download-artifact@v4
        with:
          name: math-wasm

      - name: Verify artifact
        run: ls -la math.wasm

      - name: Publish component
        run: wkg oci push ardo314/math:x.x.x math.wasm -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
